#!/usr/local/bin/python

################################################################################
# Author:     Thomas D'haenens
# License:    GPL-3.0
# Link:       https://github.com/BENEATLY/neat-community-plugins/
# Contact:    https://neatly.be/
################################################################################


# IMPORT: Standard Modules
import sqlalchemy.sql.default_comparator                                                    # SQLAlchemy Default Comparator
import sys                                                                                  # System Lib
import ujson                                                                                # JSON Lib


# FUNCTION: Read JSON File (No Logging)
def readJSONFile(file):
    with open(file, encoding='utf-8') as content:
        return ujson.load(content)


# CONFIGURATION: Determine Installation Location
locationConfig = readJSONFile('/etc/neatly/base/location.json')

# CONFIGURATION: Add Current Path to Default Python Paths
sys.path.append(locationConfig['lib'])


# IMPORT: Custom Modules
from tables import *                                                                        # Tables Lib
import actions                                                                              # Actions Lib
import basic                                                                                # Basic Lib
from plugins import createPluginLogger                                                      # Plugins Lib


# CONFIGURATION: Plugin
pluginConfig = {'plugin': {'id': 5, 'name': 'LDAP'}, 'logger': 'resources'}

# CONFIGURATION: Create Logger
logger = createPluginLogger(pluginConfig['plugin'], pluginConfig['logger'], makePreferred=True)

# CONFIGURATION: Executor
execParams = {'internal': True, 'source': 'Resources (Plugin: ' + pluginConfig['plugin']['name'] + ')'}


# CREATE: DB Connection
session = createDBSession()


# GET: Current Plugin
currentPlugin = session.query(Plugin).filter_by(id=pluginConfig['plugin']['id']).first()

# GET: Root Team
rootTeam = session.query(Team).filter_by(id=1).first()

# GET: API Actions
apiActionList = session.query(ApiAction).all()
apiActionDict = {apiAction.name: apiAction for apiAction in apiActionList}

# INSERT: ApiObjects
apiObjects = [
    {'name': 'LDAPGroup'},
    {'name': 'LDAPUserChange'}
]
[actions.createByDict(execParams, session, ApiObject, **apiObject) for apiObject in apiObjects]

# GET: New API Objects
newApiObjectList = [session.query(ApiObject).filter_by(**apiObject).first() for apiObject in apiObjects]
newApiObjectDict = {apiObject.name: apiObject for apiObject in newApiObjectList}

# DEFINE: Right
rights = []

# DEFINE: Admin Rights
skipRights = [
    {'apiObject': 'LDAPUserChange', 'apiAction': 'Edit'},
    {'apiObject': 'LDAPUserChange', 'apiAction': 'Create'}
]
rights.extend(basic.flattenArray([[{'apiObject': apiObject, 'apiAction': apiAction, 'team': [rootTeam], 'isolated': False, 'own': False, 'all': True} for apiAction in apiActionList if ({'apiObject': apiObject.name, 'apiAction': apiAction.name} not in skipRights)] for apiObject in newApiObjectList]))

# INSERT: Rights
[actions.createByDict(execParams, session, Right, **right) for right in rights]

# INSERT: Plugin Action Rights
pluginActionRights = [
    {'plugin': currentPlugin, 'action': 'use', 'team': [rootTeam], 'function': [], 'own': True, 'isolated': True, 'all': True}
]
[actions.createByDict(execParams, session, PluginActionRight, **pluginActionRight) for pluginActionRight in pluginActionRights]

# INSERT: Plugin Option Rights
pluginOptionRights = [
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Connection', 'option': 'url'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Connection', 'option': 'protocol'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Connection', 'option': 'userName'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Connection', 'option': 'password'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Connection', 'option': 'url'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Connection', 'option': 'protocol'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Connection', 'option': 'userName'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Connection', 'option': 'password'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'userName'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'firstName'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'lastName'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'mail'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'phone'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'image'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'userName'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'firstName'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'lastName'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'mail'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'phone'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Linked', 'option': 'image'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Synchronisation', 'option': 'interval'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Synchronisation', 'option': 'interval'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Synchronisation', 'option': 'fullSync'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Edit'], 'team': [rootTeam], 'function': [], 'group': 'Synchronisation', 'option': 'fullSync'},
    {'plugin': currentPlugin, 'apiAction': apiActionDict['Get'], 'team': [rootTeam], 'function': [], 'group': 'Synchronisation', 'option': 'lastSync'}
]
[actions.createByDict(execParams, session, PluginOptionRight, **pluginOptionRight) for pluginOptionRight in pluginOptionRights]

# INSERT: Plugin Options
pluginOptions = [
    {'plugin': currentPlugin, 'group': 'Connection', 'option': 'url', 'nullable': False, 'public': False, 'rawValue': None},
    {'plugin': currentPlugin, 'group': 'Connection', 'option': 'protocol', 'nullable': False, 'public': False, 'rawValue': None},
    {'plugin': currentPlugin, 'group': 'Connection', 'option': 'userName', 'nullable': False, 'public': False, 'rawValue': None},
    {'plugin': currentPlugin, 'group': 'Connection', 'option': 'password', 'nullable': False, 'public': False, 'rawValue': None},
    {'plugin': currentPlugin, 'group': 'Linked', 'option': 'userName', 'nullable': False, 'public': False, 'rawValue': None},
    {'plugin': currentPlugin, 'group': 'Linked', 'option': 'firstName', 'nullable': False, 'public': False, 'rawValue': None},
    {'plugin': currentPlugin, 'group': 'Linked', 'option': 'lastName', 'nullable': False, 'public': False, 'rawValue': None},
    {'plugin': currentPlugin, 'group': 'Linked', 'option': 'mail', 'nullable': False, 'public': False, 'rawValue': None},
    {'plugin': currentPlugin, 'group': 'Linked', 'option': 'phone', 'nullable': True, 'public': False, 'rawValue': None},
    {'plugin': currentPlugin, 'group': 'Linked', 'option': 'image', 'nullable': True, 'public': False, 'rawValue': None},
    {'plugin': currentPlugin, 'group': 'Synchronisation', 'option': 'interval', 'nullable': False, 'public': False, 'rawValue': 3600},
    {'plugin': currentPlugin, 'group': 'Synchronisation', 'option': 'fullSync', 'nullable': False, 'public': False, 'rawValue': False},
    {'plugin': currentPlugin, 'group': 'Synchronisation', 'option': 'lastSync', 'nullable': True, 'public': False, 'rawValue': None}
]
[actions.createByDict(execParams, session, PluginOption, **pluginOption) for pluginOption in pluginOptions]

# INSERT: Authentication Methods
authMethods = [{'name': 'LDAP', 'plugin': currentPlugin}]
[actions.createByDict(execParams, session, AuthenticationMethod, **authMethod) for authMethod in authMethods]
